package com.student.objectequality_equals_hashCode;

import java.util.Objects;


/**
 * Java program to demonstrate
 * 
 * 1- Objects.equals() within the equals() methods of a class. 2-
 * Integer.hashCode() methods
 * 
 * and @Override implementation of these methods
 */

public class Main {

	private Integer field1, field2;
	private static Integer hashcodeValue;
	private static Boolean b1, b2;
	private static boolean res, res2;
	
	private String name;
	private Integer id;
	private String department;
	
	private static Boolean booleanValue1;
	private static Boolean booleanValue2;
	private static  String otherName;
	private static Integer otherAge;
	private static  String otherCity;

	public static void main(String[] args) {

		// assign values to b1, b2
		b1 = Boolean.valueOf(true);
		b2 = Boolean.valueOf(false);

		// assign the result of equals method on b1, b2 to res obj − the object to
		// compare with
		res = b1.equals(b2);
		String str = "b1:" + b1 + " and b2:" + b2 + " are equal is " + res;
		System.out.println(str); // b1:true and b2:false are equal is false

		// calling equals()
		res2 = Main.equals(b1, b2);
		String str2 = "b1:" + b1 + " and b2:" + b2 + " are equal is " + res2;
		System.out.println(str2); // b1:true and b2:false are equal is false

		// calling getObject()
		hashcodeValue = Main.getObject();
		System.out.println("Hash code Value for object = " + hashcodeValue);
		
		
		Employee employee = new Employee();
		// calling hashCode()
		hashcodeValue = employee.hashCode();
		System.out.println("Hash code Value for id = " + hashcodeValue); // Hash code Value for id = 31
		
		// calling equals()
		System.out.println(employee.equals(employee));
			

		//prevents_nullpointerexception
		String a = null;
		String b = "example";
		
		
//		if (a.equals(b)) {
//			System.out.println("This will throw a NullPointerException");
//		}

//		if (a == null && a.equals(b)) {
//			System.out.println("This will print: Cannot invoke \"String.equals(Object)\" because \"a\" is null");
//		}
//
//		// adding a null check before calling .equals()
//		if (a != null && a.equals(b)) {
//			System.out.println("This won't print anything: ");
//		}
		
		
		//calling isEqual() and isEqualnew()
		booleanValue1 = Main.isEqual(otherName, otherAge, otherCity);	//with boilerplate_code
		booleanValue2 = Main.isEqualNew(otherName, otherAge, otherCity); //reducing_boilerplate_code
		
		System.out.println("Comparing Main Class fields and local parameters = " + booleanValue1); //false
		System.out.println("Comparing Main Class fields and local parameters = " + booleanValue2); //true
		
	}

	
	/**
	 * this method compares Main Class fields and local parameters
	 * with boilerplate_code
	 * 
	 * @param name
	 * @param age
	 * @param city
	 * @returns false
	 */
	public static boolean isEqual(String name, Integer age, String city) {
		return (name!= null && name.equals(otherName)) &&
			   (age != null && age.equals(otherAge)) &&
			   (city != null && city.equals(otherCity));
	}
	/**
	 * this method compares Main Class fields and local parameters
	 * 
	 * reducing_boilerplate_code
	 * @param name
	 * @param age
	 * @param city
	 * @return
	 */
	public static boolean isEqualNew(String name, Integer age, String city) {
		return 	(Objects.equals(name, otherName)) &&
				(Objects.equals(age, otherAge)) &&
				(Objects.equals(city, otherCity));
	}
	
		
	/**
	 * * Compares two objects
	 * 
	 * @param a Object − the object to compare with
	 * @param b Object − the object to compare with
	 * @return true if the Main objects represent the same value, false
	 *         otherwise.
	 */
	public static boolean equals(Object a, Object b) {
		return (a == b) || (a != null && a.equals(b));
	}

	/**
	 * Compares objects overrides equals method in class Object
	 * 
	 * @param o - the reference object of MyObject to compare with with local fields
	 * @return
	 */
	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		//Returns the runtime class of this Object. 
		if (o == null || getClass() != o.getClass())
			return false;
		MyObject myObject = (MyObject) o;

		return Objects.equals(field1, myObject.field1) && Objects.equals(field2, myObject.field2);
	}

	/**
	 * @returns an integer value, generated by a hashing algorithm.
	 */
	public static int getObject() {
		// object s_int created
		Integer s_int = new Integer("223");
		return s_int.hashCode();
	}

	/**
	 * @returns an integer value (tbc.), generated by a hashing algorithm.
	 */
	@Override
	public int hashCode() {
		return Objects.hash(field1, field2);
	}

}
